---
collections:
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 4.8.0
  - name: kubernetes.core
    version: 2.3.1
  - name: devsec.hardening
    version: 7.14.1

roles:
  - name: cloudalchemy.node_exporter
    version: 2.0.0
  - name: geerlingguy.docker
    version: 4.2.2
  - name: geerlingguy.firewall
    version: 2.5.0
  - name: geerlingguy.kubernetes
    version: 7.1.1
  - name: geerlingguy.swap
    version: 1.0.2
  - name: oefenweb.postfix
    version: v3.6.1
  - name: stefangweichinger.ansible_rclone
