---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.16.2
  - name: community.general
    version: 8.1.0
  - name: community.docker
    version: 3.5.0
