---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.15.0
  - name: community.general
    version: 7.3.0
  - name: community.docker
    version: 3.4.8
