---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.17.0
  - name: community.general
    version: 8.2.0
  - name: community.docker
    version: 3.5.0
