---
collections:
  - name: ansible.posix
    version: 1.4.0
  - name: community.general
    version: 6.0.1
  - name: community.docker
    version: 3.2.1
  - name: kubernetes.core
    version: 2.3.2
  - name: devsec.hardening
    version: 8.3.0

roles:
  - name: cloudalchemy.node_exporter
    version: 2.0.0
  - name: geerlingguy.docker
    version: 6.0.4
  - name: geerlingguy.docker_arm
    version: 5.0.0
  - name: geerlingguy.firewall
    version: 2.5.1
  - name: geerlingguy.kubernetes
    version: 7.1.1
  - name: geerlingguy.swap
    version: 1.0.2
  - name: oefenweb.postfix
    version: v3.6.1
  - name: stefangweichinger.ansible_rclone
