---
- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
  register: _pve_update_apt_cache
  until: _pve_update_apt_cache is success
  retries: 3
  delay: 2
- name: Regenerate initramfs
  ansible.builtin.command: bash update-initramfs -u
  become: yes
- name: Update Grub
  ansible.builtin.command: bash update-grub
  become: yes
- name: Reboot
  ansible.builtin.reboot:
    msg: Rebooting the hypervisor
  become: yes
