---
- name: Converge
  hosts: all
  become: yes

  tasks:
    - name: Include common role
      include_role:
        name: vladgh.system.common
      vars:
        timezone: US/Central
        local_groups:
          - name: admins
            system: yes
            sudo: yes
        local_users:
          - name: test
            comment: Testing User
            groups: admins
            append: yes
            password: mypassword
            authorized_keys:
              - ssh-ed25519 AAAA testing
        additional_packages:
          - rolldice
        apt_repositories:
          - name: Ansible
            repo: ppa:ansible/ansible
        pip_install_packages: [pip-install-test]
        pip_user_install_packages:
          - user: test
            packages: [colorama]
            state: latest
        cron_jobs:
          - name: Testing
            minute: '0'
            job: ls -lah > /dev/null
        mounts:
          - name: Test
            path: /mnt/boot
            src: /boot
            opts: bind
            fstype: none
        systemd_mounts:
          - name: SystemD Mount Test
            automount: no
            what: /srv
            where: /mnt/srv
            options: bind
            type: none
          - name: SystemD Auto Mount Test
            automount: yes
            what: localhost:/media
            where: /mnt/media
            options: _netdev,auto
            type: nfs
        install_ca_certificates: yes
        fail2ban_enabled: yes
        unattended_upgrades_autoupdate_enabled: yes
        unattended_upgrades_autoupdate_reboot: "true"
        unattended_upgrades_autoupdate_mail_to: "root"
        unattended_upgrades_autoupdate_mail_on_error: yes
