---
- name: Ensure NFS utilities are installed
  ansible.builtin.package:
    name: "{{ nfs_server_packages }}"
    state: present

- name: Generate NFS shares
  when: nfs_exports is defined and nfs_exports | length
  block:
    - name: Ensure directories to export exist
      ansible.builtin.file:  # noqa 208
        path: "{{ item.strip().split()[0] }}"
        state: directory
      loop: "{{ nfs_exports }}"

    - name: Generate exports file
      ansible.builtin.template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
      notify: Reload NFS

    - name: Ensure NFS is running
      ansible.builtin.service:
        name: "{{ nfs_server_daemon }}"
        state: started
        enabled: true
      tags:
        - molecule-notest
