---
- name: Converge
  hosts: all
  become: yes
  roles:
    - ./roles/proxmox
  pre_tasks:
    - name: Ensure required directories
      ansible.builtin.file:
        path: /etc/lvm
        state: directory
        mode: 0777
      with_items:
        - /etc/lvm
        - /var/log/chrony
        - /run/chrony
    - name: Ensure required files
      ansible.builtin.copy:
        content: ''
        dest: "{{ item }}"
        force: no
        group: root
        owner: root
        mode: 0664
      with_items:
        - /etc/default/grub
        - /etc/lvm/lvm.conf
  vars:
    skip_reboot: yes
    skip_grub: yes
    skip_initramfs: yes
    proxmox_enable_chrony: yes
    proxmox_gpu_passthrough_enabled: yes
    proxmox_lvm_thin_pool_autoextend: yes
    proxmox_zfs_tune: yes
