---
- name: Install role dependencies
  ansible.builtin.apt:
    name:
      - gnupg2
      - apt-transport-https
    update_cache: true
    state: present

- name: Add Hashicorp Apt signing key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc
    mode: 0644

- name: Add Hashicorp repo configuration
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
    state: present
  register: hashicorp_repo

- name: Install Hashicorp Packer
  ansible.builtin.apt:
    name: packer
    state: present

- name: Install Hashicorp Terraform
  ansible.builtin.apt:
    name: terraform
    state: present

- name: Install Hashicorp Vault
  ansible.builtin.apt:
    name: vault
    state: present
