---
- name: Generate Configuration Directory
  ansible.builtin.file:
    path: /etc/nut
    state: directory
    mode: '0755'

- name: Generate Server Configuration
  ansible.builtin.import_tasks: server.yml
  when: >
    nut_mode is defined and
    (
      nut_mode == 'netserver' or
      nut_mode == 'standalone'
    )

- name: Generate Client Configuration
  ansible.builtin.import_tasks: client.yml
  when: >
    nut_mode is defined and
    (
      nut_mode == 'netserver' or
      nut_mode == 'standalone' or
      nut_mode == 'netclient'
    )

- name: Generate NUT Mode Configuration
  ansible.builtin.template:
    src: nut.conf.j2
    dest: /etc/nut/nut.conf
    owner: root
    group: nut
    mode: '0640'
  notify:
    - Restart NUT Server
    - Restart NUT Client

- name: Service State
  ansible.builtin.import_tasks: state.yml
