---
- name: Ensure NUT Server Service
  ansible.builtin.service:
    name: nut-server
    enabled: true
    state: started
  when: >
    nut_mode is defined and
    (
      nut_mode == 'netserver' or
      nut_mode == 'standalone'
    )

- name: Ensure NUT Client Service
  ansible.builtin.service:
    name: nut-client
    enabled: true
    state: started
  when: >
    nut_mode is defined and
    (
      nut_mode == 'netserver' or
      nut_mode == 'standalone' or
      nut_mode == 'netclient'
    )
