---
- name: Restart SSH Daemon
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart LoginD
  ansible.builtin.service:
    name: systemd-logind
    state: restarted

- name: Update trusted CA certificates
  ansible.builtin.command: /usr/sbin/update-ca-certificates --fresh

- name: Restart SystemD mount
  ansible.builtin.systemd:
    name: "{{ item.where[1:] | replace('/', '-') }}.mount"
    state: "{{ item.service_state | default('started') }}"
    enabled: "{{ item.service_enabled | default(true) }}"
    daemon_reload: true
  loop: "{{ systemd_mounts }}"
  when: ( item.automount is not defined ) or ( not item.automount )

- name: Restart SystemD auto mount
  ansible.builtin.systemd:
    name: "{{ item.where[1:] | replace('/', '-') }}.automount"
    state: "{{ item.service_state | default('started') }}"
    enabled: "{{ item.service_enabled | default(true) }}"
    daemon_reload: true
  loop: "{{ systemd_mounts }}"
  when: item.automount is defined and item.automount
