---
- name: Add extra Bash aliases
  ansible.builtin.lineinfile:
    dest: "{{ item.dest | default('~/.bashrc') }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: 0644
    create: true
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "alias {{ item.alias }}="
    state: "{{ item.state | default('present') }}"
  loop: "{{ bash_extra_aliases }}"
