---
- name: Ensure GnuPG package is installed
  ansible.builtin.apt:
    name: gnupg2
    update_cache: yes

- name: Add extra APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    codename: "{{ ansible_distribution_release | default(omit) }}"
    filename: "{{ item.filename | default(omit) }}"
    update_cache: "{{ item.update_cache | default(no) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ apt_repositories }}"

- name: Update Apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: _update_apt_cache
  until: _update_apt_cache is success
  retries: 3
  delay: 2
