---
- name: Install CA Certificates
  ansible.builtin.package:
    name: ca-certificates
    state: present

- name: Install MSMTP and MailX
  ansible.builtin.apt:
    name:
      - msmtp
      - msmtp-mta
      - mailutils
    state: present
    update_cache: true

- name: Configure MSMTP
  ansible.builtin.template:
    src: etc/msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: 0644

- name: Configure aliases
  ansible.builtin.template:
    src: etc/aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644

- name: Setup alternatives for MTA
  community.general.alternatives:
    name: mta
    link: /usr/sbin/sendmail
    path: /usr/bin/msmtp
