---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include dns role
      ansible.builtin.include_role:
        name: vladgh.system.dns
      vars:
        cloudflare_ddns_updater_enabled: true
