---
- name: Enable backports on Debian
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    filename: backports
    update_cache: true
  when: ansible_distribution_release == 'buster'

- name: Ensure WireGuard Packages
  ansible.builtin.package:
    name:
      - wireguard
      - wireguard-tools
      - qrencode
      - iptables
    state: present

- name: Ensure Wireguard Directory
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: 0755

- name: WireGuard Configuration
  when: wireguard_config is defined and wireguard_config
  tags:
    # for the first run the default ipv4 interface is eth0 but for subsequent runs is wgX
    - molecule-idempotence-notest
  block:
    - name: Generate Configuration
      ansible.builtin.template:
        src: wg.conf.j2
        dest: "/etc/wireguard/{{ item.key }}.conf"
        owner: root
        group: root
        mode: 0600
      no_log: true
      loop: "{{ wireguard_config }}"
      notify: Restart WireGuard

    - name: Start and Enable WireGuard Service
      ansible.builtin.service:
        name: "wg-quick@{{ item.key }}"
        state: started
        enabled: true
      no_log: true
      loop: "{{ wireguard_config }}"

- name: Create a resolvconf link
  ansible.builtin.file:
    src: /usr/bin/resolvectl
    dest: /usr/local/bin/resolvconf
    state: link
