name: Test

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published

jobs:
  changes:
    name: Detect file changes
    runs-on: ubuntu-22.04
    outputs:
      scenario: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Detect changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: .github/filters.yml
  test:
    name: "Test scenario ${{ matrix.scenario }} on ${{ matrix.os }}"
    runs-on: ubuntu-22.04
    needs: changes
    if: ${{ needs.changes.outputs.scenario != '[]' && needs.changes.outputs.scenario != '' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu2404
          - ubuntu2204
          - debian12
          - debian11
        scenario: ${{ fromJSON(needs.changes.outputs.scenario) }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: ansible_collections/vladgh/system
      - name: Molecule test
        uses: gofrolist/molecule-action@ef5349b7ea7f971eac0bba613a7e06b240993ad9 # v2.7.24
        with:
          molecule_command: test
          molecule_options: --debug --base-config molecule/base.yml
          molecule_args: --scenario-name ${{ matrix.scenario }}
          molecule_working_dir: ansible_collections/vladgh/system
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
          MOLECULE_DISTRO: ${{ matrix.os }}
      #   continue-on-error: true
      # - name: Debugging with tmate
      #   uses: mxschmitt/action-tmate@v3.18
